[shell]
disabled = false

[username]
show_always = true
format = '[$user](fg:bright-purple)'

[hostname]
ssh_only = false
format = '@[$hostname](fg:bright-cyan)'

[directory]
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"
format = ":[$path](fg:bright-yellow) "

[git_branch]
always_show_remote = true

[status]
disabled = false
style = "fg:#FF3333"
success_symbol = "\u2713"
#symbol = "\uf06a"
#format = "[$symbol]($style) "

[battery]
disabled = true
